### ISSUE TITLE
a category for 'I don't know' would be helpful

### ISSUE THREAD

**Issue by goetzk** [amboar/fpos#10]
I've come across a couple of instances where something has been bought (4 months ago) and I'm not sure what it was. Some way to indicate that would be helpful, as i'm using entertainment as a catch all at the moment.

**Comment by amboar** [comment]
There are also issues with the graphing and adding new categories, though that would probably solved by switching to a web-based backend, away from the "generate raw matplotlib graphs as a backend" approach. There also has to be a concept of a backend, which there isn't currently.

My recommendation is to use Cash, as above.
