### ISSUE TITLE
Link to full explaination of categories

### ISSUE THREAD

**Issue by goetzk** [amboar/fpos#11]
Hi,
On the assumption that the categories used are documented in full somewhere on the Money Smart website could you include a link to that place in the Overview section of README.md? There are a number of things I encountered when trialing fpos which I couldn't fit in to the provided categories from the descriptions available.

examples i can remember having trouble with:
* child pocket money
* travel that isn't holidays (conferences, representative sport)
* fees (bank fees, a bounced transaction, interest on loan though i put that in commitment)

**Comment by amboar** [comment]
Not really!
